# Generated by Django 4.1.5 on 2023-12-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_create_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_create',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_create',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
