# Generated by Django 4.1.5 on 2023-12-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_create_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_create',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post_create',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
