# Generated by Django 4.1.5 on 2023-12-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_all_meta_post_create_meta_scripts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_create',
            old_name='meta_scripts',
            new_name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='post_create',
            name='meta_tags',
        ),
        migrations.AddField(
            model_name='post_create',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post_create',
            name='meta_decription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post_create',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_create',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
