# Generated by Django 4.1.5 on 2023-12-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_meta_scripts_post_create_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_create',
            name='meta_title',
        ),
    ]
