# Generated by Django 5.0 on 2023-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_post_create_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_create',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='autopost/'),
        ),
    ]
