# Generated by Django 5.0 on 2023-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_create_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_create',
            name='meta_decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
