# Generated by Django 5.0 on 2023-12-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_create',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Python', to='api.blog_category'),
        ),
    ]
