# Generated by Django 5.0 on 2023-12-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_post_create_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_create',
            old_name='meta_decription',
            new_name='meta_description',
        ),
    ]
