# Generated by Django 5.0 on 2023-12-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_meta_decription_post_create_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_category',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
